name: Build and Release Flutter App for Multiple Linux Architectures

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm, arm64, x64]
        cpu: [generic, pi3, pi4]
    steps:
    - uses: actions/checkout@v2

    - name: Read pubspec.yaml
      run: |
        SDK_CONSTRAINT=$(grep 'sdk: ' "./pubspec.yaml" | awk '{print $2}' | head -1 | tr -d "'" | sed "s/>=//g")
        FLUTTER_VERSION=$(echo "$SDK_CONSTRAINT" | awk '{print $1}')
        echo "FLUTTER_VERSION=${FLUTTER_VERSION}" >> $GITHUB_ENV
        APP_VERSION=$(grep 'version: ' "./pubspec.yaml" | awk '{print $2}')
        echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

    - name: Debug output
      run: |
        echo "Flutter SDK Constraint: $SDK_CONSTRAINT"
        echo "App Version: $APP_VERSION"

    # Install flutterpi_tool
    - name: Install flutterpi_tool
      run: |
        flutter pub global activate flutterpi_tool

    # Build App Bundle
    - name: Build App Bundle
      run: |
        flutterpi_tool build --arch=${{ matrix.arch }} --cpu=${{ matrix.cpu }} --release

    - name: Archive release build
      run: tar -czvf hallaos-${{ matrix.arch }}-${{ matrix.cpu }}-release-build.tar.gz ./build/flutter_assets/

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        tag_name: ${{ env.APP_VERSION }}-${{ matrix.arch }}-${{ matrix.cpu }}
        release_name: Release ${{ env.APP_VERSION }} for ${{ matrix.arch }}-${{ matrix.cpu }}
        draft: false
        prerelease: false

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./linux-${{ matrix.arch }}-${{ matrix.cpu }}-release-build.tar.gz
        asset_name: linux-${{ matrix.arch }}-${{ matrix.cpu }}-release-build.tar.gz
        asset_content_type: application/gzip
